version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=product_service_db
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=product-service
      # Add these for better Eureka integration
      - SPRING_APPLICATION_NAME=product-service
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
    depends_on:
      - mongodb
    networks:
      - spring-mongo-network
      - microservices-network

  mongodb:
    image: mongo:latest

    volumes:
      - mongodb_data:/data/db
    networks:
      - spring-mongo-network

networks:
  spring-mongo-network:
    driver: bridge
  microservices-network:
    external: true

volumes:
  mongodb_data: